Indent with hard tabs

diff --git a/usr/local/sbin/resticw b/usr/local/sbin/resticw
--- a/usr/local/sbin/resticw
+++ b/usr/local/sbin/resticw
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-
 DOC="A little wrapper over restic just to handle profiles and environment loading.
 
 Usage:
@@ -137,8 +136,8 @@ profile_file="${ENV_DIR}/${__profile}.env"
 [[ ! -f "$profile_file" ]] && echo "Invalid profile: No such environment file ${profile_file}" && exit "$ERR_NO_SUCH_PROFILE"
 
 if [[ ! -r "$profile_file" ]]; then
-  echo "Error: could not read the environment file ${profile_file}. Are you running this script as the correct user? Maybe try sudo with the right user."
-  exit "$ERR_PROFILE_NO_READ_PERM"
+	echo "Error: could not read the environment file ${profile_file}. Are you running this script as the correct user? Maybe try sudo with the right user."
+	exit "$ERR_PROFILE_NO_READ_PERM"
 fi
 
 echo -e "‣ Using profile: ${__profile}  --  (${profile_file})\n"
